### PR TITLE
Replace flake8 and isort by ruff

### LINKED ISSUE #427: Use ruff for linting
I think @lwasser and I would be excited to use ruff as a linting tool. It could replace both flake8 and isort.

It also offers many more check that we could activate.

I've used it on a couple of projects. It works great and is incredibly fast but I think the best feature is that it can autofix many of the errors!

### PR DESCRIPTION
**Pull request by enadeau**
closes #427

## Description

Configure ruff like flake8 was and replace it is CI

Also replace isort

## Type of change

Select the statement best describes this pull request.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] This is a documentation update
- [x] Other (please describe) Infrastructure change

## Does your PR include tests

If you are fixing a bug or adding a feature, we appreciate (but do not require)
tests to support whatever fix of feature you're implementing.

- [ ] Yes
- [ ] No, i'd like some help with tests
- [x] This change doesn't require tests

## Did you include your contribution to the change log?

- [x] Yes, `changelog.md` is up-to-date.

### CODE REVIEW

**Comment by enadeau** [comment]
pre-commit.ci autofix

**Comment by enadeau** [comment]
pre-commit.ci autofix

**Comment by enadeau** [comment]
pre-commit.ci autofix

**Comment by enadeau** [comment]
Okay I think this is mostly done. I've been trying to fix the pre-commit failure using precommit.ci autofix but it doesn't seems to work. If anyone know why I'd be happy to learn that otherwise I'll just push the fixes

**Comment by lwasser** [comment]
pre-commit.ci autofix

**Comment by lwasser** [comment]
pre-commit.ci autofix

**Comment by lwasser** [comment]
@enadeau something really odd is happening with the precommit.ci bot and i don't think it has anything to do with our build setup (but i need to try it in another repo). what seems to be happening is that it's running but not fixing the pr / adding a commit as it should do. so i'd say for now let's just push a fix and merge this. in the meantime i'll dig into what might be causing the bot to not create the update commit that it should be creating when we run the autofix command!

**Comment by enadeau** [comment]
Okay everything is ready just waiting for approval to merge

**Review by lwasser — APPROVED** [review]
This looks good! i'll go ahead and merge it.

**Comment by lwasser** [comment]
thanks for this @enadeau !!! 🚀

**Pull request merged**
