### PR TITLE
Use Pydantic V2 with V1 compatibility mode

### LINKED ISSUE #379: New pydantic release -- parse_datetime has been removed & is causing errors in our test runs.
Pydantic has JUST release 2.0 and our builds are not failing due to this:

[tests are also failing ](https://github.com/stravalib/stravalib/actions/runs/5425675105/jobs/9866739005#step:11:24)

`pydantic.errors.PydanticImportError: `pydantic.datetime_parse:parse_datetime` has been removed in V2.`

locally tests run on my machine but i'm still running pydantic 1.10.9. i just pushed a pinned version of pydantic to ensure this is indeed the issue.

### PR DESCRIPTION
**Pull request by soh55**
closes #379

_The text above will ensure the issue will be closed when this PR is merged_

## Description

I added [Pydantic V1 backward compatibility features](https://docs.pydantic.dev/latest/migration/#continue-using-pydantic-v1-features) so users can move to a newer Pydantic version. Need to find some time to perform the actual migration.

Reference issue: #379 

## Type of change

Select the statement best describes this pull request.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] This is a documentation update
- [ ] This is a infrastructure update (docs, ci, etc)
- [ ] Other (please describe)

## Does your PR include tests

If you are fixing a bug or adding a feature, we appreciate (but do not require)
tests to support whatever fix of feature you're implementing.

- [ ] Yes
- [ ] No, i'd like some help with tests
- [X] This change doesn't require tests

## Did you include your contribution to the change log?

- [x] Yes, `changelog.md` is up-to-date.

_If you are having a hard time getting the tests to run correctly feel free to
ping one of the maintainers here!_

### CODE REVIEW

**Comment by jsamoocha** [comment]
Hi, thanks for this contribution! This is really useful since it allows dependent projects to upgrade to pydantic V2 without clashes.

Can you please update the changelog so we can include this change in a new release soon?

**Comment by yihong0618** [comment]
nice catch.

**Review by yihong0618 — APPROVED** [review]

**Review by lwasser — APPROVED** [review]
This looks awesome!  thanks @soh55 🚀 

@jsamoocha if you want, i'm happy to make the release when we're ready / when we merge this!

**Comment by soh55** [comment]
@jsamoocha @yihong0618 @lwasser Just went for a walk and realized that my version requirements for pydantic >=1.10.9 is probably a goof. It'd be alright if this package required V2 for the next release but I think it'll break for users using V1. I can see if I can write extra version handling code to account for both versions but I wasn't sure about your release plan.

**Comment by jsamoocha** [comment]
It looks like we need to take a step back. I also reviewed this PR too quickly because I now see there were changes in `strava_model.py`, which is generated and cannot be edited by us. This change will need to involve the configuration of the data model generator (or possibly even a PR in that repo for supporting importing `pydantic.v1.BaseModel`).

**Pull request merged**
