### PR TITLE
Feature: Pydantic model API redesign 

### LINKED ISSUE #248: Discussion: Consider Pydantic as a replacement for homegrown Models / Attributes framework ?
A key value-add, in my opinion, for Stravalib is the modeling of the entities from Strava in a way that makes them easy for API users to integrate with their applications.  Not just the stronger typing that is increasingly helpful in larger Python applications, but also handling speed/distance units and conversions.   Since this library has been written, we've had some great new packages added to the python ecosystem.  We've also had newer python introduce native dataclasses.  For awhile [Marshmallow](https://marshmallow.readthedocs.io/en/stable/) was something I'd been looking at to change how we were modeling the Strava entities; however, I think the clear front-runner in recent years is [Pydantic](https://pydantic-docs.helpmanual.io/). 

I think the main benefit to this would be embracing what is becoming (or feels like it is becoming) the standard for modeling (de)serializable data classes in python.  Pydantic is easily customized to handle more complex deserialization (or serialization) of these dataclass models.

More thought would need to be given to how to handle units & type conversions, the current way of expressing the different detail levels and which attributes are present, etc.  (The latter may not be strictly necessary either?)

I haven't fully thought this through or proven it out; this is more just an observation that stravalib rolls its own (de)serialization & modeling framework, which may be better handled by purpose built tooling in 2022.  So just wanted to propose this idea for consideration if there is a plan to do a major version bump & break backwards compatibility.  (This would also mean supporting only newer Python 3, but I think that is probably acceptable with a major version bump.)

### PR DESCRIPTION
**Pull request by jsamoocha**
closes #248

## Description

This replaces the existing domain model in the modules `model.py` and `attributes.py` by a new domain model that is based on pydantic. The officially documented Strava API is generated into a new module `strava_model.py` whenever it changes. There is backward compatibility for lazy loading using the bound client, unit conversion, and rich types for, e.g., `timedelta`-based durations.

The documentation has also been updated to correctly show the pydantic-based model classes.

For a full explanation and discussion of the individual changes, see #302, #315, #316, #322, #324, and #329.

## Type of change

- [x] Other (please describe)

Refactoring of internal domain model.

## Does your PR include tests

This branch was available as a release candidate for community testing during the last 2 weeks, without any reported issues.

## Did you include your contribution to the change log?

- [x] Yes, `changelog.md` is up-to-date.

### CODE REVIEW

**Comment by jsamoocha** [comment]
Whenever we merge, let's not squash this one to preserve references to the individual PRs

**Comment by lwasser** [comment]
yay! i'm looking into the documentation error. @jsamoocha is there anything new in this PR that warrants more testing? or specific parts of this to review? we've been working on this for a while (mostly you i just run the code :) ... and i did test on the release we did against this branch.  many thanks.

**Comment by lwasser** [comment]
ok another note - i'm going to have to build the docs locally to try to figure out what is going on. more later.

**Comment by lwasser** [comment]
found this - https://github.com/pydata/pydata-sphinx-theme/issues/1220

**Comment by jsamoocha** [comment]
> is there anything new in this PR that warrants more testing?

No, nothing new except your fix to the documentation (thanks for looking into that!)

**Review by lwasser — APPROVED** [review]
ok awesome! let's merge this! such a huge effort  - thank you for spending so much time  redesigning our API  @jsamoocha !!

**Comment by lwasser** [comment]
> > is there anything new in this PR that warrants more testing?
> 
> No, nothing new except your fix to the documentation (thanks for looking into that!)

no problem. it was just a tiny bug so not a big deal to fix!

**Pull request merged**
