### PR TITLE
Add: pull request templates to repo

### PR DESCRIPTION
**Pull request by lwasser**
This just adds pull request templates here so we can more easily merge #290

### CODE REVIEW

**Comment by lwasser** [comment]
@jsamoocha this adds the PR templates to a separate pr so we can focus on the content in the other open pr.

**Comment by lwasser** [comment]
ok!
✅ pr templates have been removed frm this PR and added to #294 
✅ i moved the test content paragraph into the warning block
✅  and i believe all other items have been addressed.

Let me know if there is anything left here to do @jsamoocha !

**Review by jsamoocha — APPROVED** [review]
Thanks, LGTM!

**Review by yihong0618 — APPROVED** [review]

**Comment by lwasser** [comment]
thank you both!! merging this as well :) we can always modify the pr templates if they don't work out as well but i'm hoping they help streamline contributions.

**Pull request merged**
