### PR TITLE
Fix: update Readthedocs config file and add autobuild permissions for prs

### LINKED ISSUE #411: Docs are failing due to deprecation of some of the rtd.yml file config settings
Yikes - i promise i'll start knocking off some of these issues i'm opening. i just got several messages that our docs are failing. i believe the fix will be to update our yaml file to NOT fail on warnings. i believe the issue is that pydantic JSON not rendering issue that was identified by @enadeau . it's a warning but failing the build. IF the fix i have in mind works it will be simple and fast. but we won't know until we try to update the config file

### PR DESCRIPTION
**Pull request by lwasser**
closes #411

## Description

Our docs are currently failing builds in read the docs.

## Type of change

Select the statement best describes this pull request.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [x] This is a documentation update
- [ ] Other (please describe)

## Does your PR include tests

If you are fixing a bug or adding a feature, we appreciate (but do not require)
tests to support whatever fix of feature you're implementing.

- [ ] Yes
- [ ] No, i'd like some help with tests
- [x] This change doesn't require tests

## Did you include your contribution to the change log?

- [x] Yes, `changelog.md` is up-to-date.

i didn't update the changelog on this one but could. it's pretty minor if this fix works

### CODE REVIEW

**Comment by lwasser** [comment]
This should also add a documentation build from RTD allowing us to preview docs - not sure if it will work but i setup the webhook for it to work while fixing (maybe) the build. let's see...

**Comment by lwasser** [comment]
Screen Shot 2023-08-16 at 1 31 09 PM
eeks. 🤯 will figure this out just not now... :(

**Comment by lwasser** [comment]
It was a webhook permissions issue and a deprecation of the way RTD processes the YAML file syntax. 

Below you can see the RTD build now added to our pr's. This will allow us to preview docs before merging a pr!
 
Screen Shot 2023-08-16 at 4 42 02 PM

just click on the `details` next to the CI run and you'll get to preview the current state of our docs. in theory we could then remove the docs action if we wish and just use RTD as it provides a preview. but we might want to see what it looks like when it fails first. as i setup our docs build to also print out broken links for easier identification of issues. this is ready to review now.

**Review by enadeau — APPROVED** [review]
Never worked with RTD but that looks good to me. I like the preview!

**Comment by lwasser** [comment]
ok great! i'll merge this as if i rebase the other pr, it should fix the build there. essentially some of our config file had deprecated syntax!!

**Pull request merged**
