### PR TITLE
Fix: move stravalib to src/ layout and add nox build steps

### PR DESCRIPTION
**Pull request by lwasser**
closes #397
This is the second part of upgrading to nox - adding build and cleanup steps and moving to a src/ layout for easier testing. 

## Type of change

Select the statement best describes this pull request.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] This is a documentation update
- [x] Other (please describe) - infrastructure update

## Does your PR include tests

If you are fixing a bug or adding a feature, we appreciate (but do not require)
tests to support whatever fix of feature you're implementing.

- [ ] Yes
- [ ] No, i'd like some help with tests
- [x] This change doesn't require tests

## Did you include your contribution to the change log?

- [x] Yes, `changelog.md` is up-to-date.

### CODE REVIEW

**Comment by lwasser** [comment]
This only looks like a massive PR because i moved all of our code into a new directory. but i didn't actually modify any of the files - only the file structure. i did modify the noxfile, our init.py and other config files to work in the new structure.

**Comment by lwasser** [comment]
Ok - things are working generally now but i have to do a bit more testing. 
Once i'm happy with things i'll update docs on the build SDist / wheel / package distribution changes that i made associated with the src/ layout. but overall the output wheel is looking generally ok and things are installing, running as they should using nox as the foundation for all of our dev steps.

**Comment by lwasser** [comment]
ok i'll run pre-commit after a review. but if someone wants to take this for a test drive that would be great. i may have missed things as there were a lot of small changes that were required to get this all working... so let me know what you catch!!

**Review by enadeau — COMMENTED** [review]
Hey very nice work. I have to. I've cloned and could at least run the test and build the doc. I don't know if there's anything specific you think I should try.

Otherwise, I have two comments:
1. I think it's necessary to run mypy on multiple version, as it will always return the same result.
2. I wonder if we should also move the tests outside the of the stravalib folder. The standard setup is to have the tests folder alongside the src folder

**Comment by lwasser** [comment]
> * I think it's necessary to run mypy on multiple version, as it will always return the same result.

@enadeau can you please be a bit more specific. do you mean it's not necessary to run it across versions? the reason why i thought we should was because previously we were finding some annotation types failed on some python versions. I think there are still a few things that 3.9 won't support right? or am i wrong? i'm happy to move it back to a single version build if we really don't need it. i'm just explaining my rational which may or may not be correct! 

Also are you referring to the action / nox build or both? with a bit more info i can adjust the pr accordingly.


> * I wonder if we should also move the tests outside the of the stravalib folder. The standard setup is to have the tests folder alongside the src folder

We could. there is a lot of debate around this in the packaging community right now. if we do move it i can make sure that setuptools atleast bundles tests in our SDist. but technically they really aren't needed in our wheel given this is a pure python package. some feel strongly tests belong in the code dir because it then ships in all builds automagically. and others argue for it as it's own separate folder for other numerous reasons which are mainly driven by organization and structural preferences. i don't have a strong opinion. If you'd  prefer it, i can move it and then set things up so tests ship in the SDIst only, I can!

**Comment by enadeau** [comment]
### About mypy:

The type checking is not dependent on python version. Mypy is doing static analysis, meaning it is not running any of our code. The results will be influenced by the target version we set but not the version of python that runs mypy.

It's best to think of it as the other linter. It wouldn't make sense to run flake8, black or isort on multiple python versions

If we use python feature from version >3.9 the unit test have to catch this

### About the tests folder:

I didn't know there is big debate about that. I've just always seen in outside the code in the project I worked on. Never quite seen the point of having them package in the distribution as well.

I don't really have a strong opinion on it either so let's go the easiest way and to nothing for now?

**Comment by enadeau** [comment]
> I think it's necessary to run mypy on multiple version, as it will always return the same result.

Also realizing that I meant to says "I think it is NOT necessary"...

**Comment by lwasser** [comment]
ok great... so 

1. i'll pull the multi-python version run from nox and the ci build - no problem
2. regarding tests - if that can wait (i'm happy to open an issue) that would be good. i just ran into a weird tricky situation where we're importing a fixture from conftest but i don't know how to do that if the tests are not a part of the package.

so that is failing now. 

As for the debate - i think i've been in too many packaging discussions with people debating about what packages should look like 😆  but again i don't have an opinion here at all. if we decide to make that move which we can. I'll open another pr just because i'm not sure about the module import part but i'm sure i can figure it out (or maybe you know?). pushing a few fixes in a bit here...

**Comment by lwasser** [comment]
ok @enadeau !! thank you for the mypy explanation. I've reverted the mypy run to be single python version only. And i've left tests in the src/stravalib dir for now and will look into conftest imports at another time.  let me know if you catch anything else!! ✨

**Review by enadeau — APPROVED** [review]
I don't have anything else to say. LGTM

**Comment by lwasser** [comment]
great!! i'll merge this now. then will do a test install from test-pypi!! just to double check everything.

**Pull request merged**
