### PR TITLE
Remove: functional test suite that we are no longer using

### LINKED ISSUE #457: Fix: Remove old functional test suite
We have a functional test suite that has dated tests that also rely upon a user token / need to be run locally as is now. It makes the most sense to remove those tests to keep or code base clean. This should be a quick and easy pr!

### PR DESCRIPTION
**Pull request by lwasser**
closes #457 

As discussed in that issue this just removes the old test suite that we no longer use. 

## Description

I removed the entire functional/ dir within the tests/ dir

## Type of change

Select the statement best describes this pull request.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] This is a documentation update
- [x] This is a infrastructure update (docs, ci, etc)
- [ ] Other (please describe)

## Does your PR include tests

If you are fixing a bug or adding a feature, we appreciate (but do not require)
tests to support whatever fix of feature you're implementing.

- [ ] Yes
- [ ] No, i'd like some help with tests
- [x] This change doesn't require tests

## Did you include your contribution to the change log?

- [x] Yes, `changelog.md` is up-to-date.

### CODE REVIEW

**Comment by enadeau** [comment]
Sounds like a good idea to remove test that requires a user token to run and that are never actually run. They've quite confused me since I joined.

 What does the coverage.xml file has to do with that?

**Comment by lwasser** [comment]
> What does the coverage.xml file has to do with that?

@enadeau are you referring to the code cover coverage.xml report? if i'm understanding correctly, that is the file that we want to upload to codecov.io for coverage reports (and those nice messages that it used to add to our pr's). it was working for a while but it stopped working and i'm not sure why yet. but locally i'm getting odd returns when i run the test suite. 

i started to try to address it here #469  but i don't think it's a token issue. if you have any ideas please let me know or comment on that pr! i always feel like i get those things working by accident if you know what i mean? 😆 

maybe we could look at it in the other pr or in an issue separate from this pr?

**Comment by lwasser** [comment]
oh my apologies - i need to remove htat file - i commit it by mistake but i'm not actually sure how that happened as i can't get that report to generate locally now 😆 i'll fix that before we merge this. oops

**Comment by lwasser** [comment]
fixed! coverage.xml is removed (and added to the .gitignore. 
i missed that @enadeau thank you for catching it.

**Comment by lwasser** [comment]
ok @enadeau does this all look good to you know to merge?

**Comment by enadeau** [comment]
Yes let's merge that

**Review by enadeau — APPROVED** [review]

**Pull request merged**
