### PR TITLE
FIX: corrects src path

### PR DESCRIPTION
**Pull request by jsamoocha**
This workflow config was not updated after adding the `src/` dir, causing the automatic pull request to fail.

- [x] This is an infrastructure update (docs, ci, etc)

## Does your PR include tests

If you are fixing a bug or adding a feature, we appreciate (but do not require)
tests to support whatever fix of feature you're implementing.

- [x] This change doesn't require tests

### CODE REVIEW

**Comment by jsamoocha** [comment]
Although the strava API change PR bot runs again, it seems to generate code that conflicts with some editing we did (see some of the typos in comments that originate from Strava.

Also, the generated container types are not the "plain" python `list,` but rather `typing.List`, which is odd since we set 3.9 as the python version for the generator. Will need to look into that later (that's in the strava_swagger2pydantic repo).

Finally, I keep seeing these node16 deprecation warnings, even after updating the action dependencies in the strava_swagger2pydantic repo and making a new release. Any ideas about that are welcome 🙏.

**Comment by yihong0618** [comment]
> Although the strava API change PR bot runs again, it seems to generate code that conflicts with some editing we did (see some of the typos in comments that originate from Strava.
> 
> Also, the generated container types are not the "plain" python `list,` but rather `typing.List`, which is odd since we set 3.9 as the python version for the generator. Will need to look into that later (that's in the strava_swagger2pydantic repo).
> 
> Finally, I keep seeing these node16 deprecation warnings, even after updating the action dependencies in the strava_swagger2pydantic repo and making a new release. Any ideas about that are welcome 🙏.

node16 is easy to fix.
just update the checkout@version and python@version in Actions I will fix them in another pull request

**Review by yihong0618 — APPROVED** [review]
Nice catch

**Comment by enadeau** [comment]
> Also, the generated container types are not the "plain" python `list,` but rather `typing.List`, which is odd since we set 3.9 as the python version for the generator. Will need to look into that later (that's in the strava_swagger2pydantic repo).

This is something I patched at the time by using ruff to update the syntax to the most modern one. See https://github.com/stravalib/strava_swagger2pydantic/pull/7/files

I don't have time to investigate that now but maybe this stopped working after some changes?

**Comment by yihong0618** [comment]
> > Although the strava API change PR bot runs again, it seems to generate code that conflicts with some editing we did (see some of the typos in comments that originate from Strava.
> > Also, the generated container types are not the "plain" python `list,` but rather `typing.List`, which is odd since we set 3.9 as the python version for the generator. Will need to look into that later (that's in the strava_swagger2pydantic repo).
> > Finally, I keep seeing these node16 deprecation warnings, even after updating the action dependencies in the strava_swagger2pydantic repo and making a new release. Any ideas about that are welcome 🙏.
> 
> node16 is easy to fix. just update the checkout@version and python@version in Actions I will fix them in another pull request

no need another pr change to `peter-evans/create-pull-request@v6` seems ok

**Comment by jsamoocha** [comment]
> This is something I patched at the time by using ruff to update the syntax to the most modern one. See https://github.com/stravalib/strava_swagger2pydantic/pull/7/files

Thanks for that hint; I now see how ruff is used to post-process the generated file. Will dig into that later...

**Comment by jsamoocha** [comment]
I think all the issues mentioned are addressed by now, so please give this another review (as well as the new tiny PR in the strava_swagger2pydantic repo). After merging these two, we can try to rerun the bot. I'll remove the existing PR generated by the bot.

**Review by lwasser — APPROVED** [review]
ahh shoot i didn't even think about this workflow. great fix @jsamoocha  this means we haven't been getting updates for a while?! 🙈 let's merge!

**Comment by lwasser** [comment]
let's merge this! @yihong0618 nailed it. those node errors are what i attempted to fix in #475 but it seems like i missed a critical workflow! they are popping up in everyone's ci workflows that aren't up to date now!

**Pull request merged**
