### PR TITLE
Publish type annotations

### LINKED ISSUE #373: Working towards better type annotation
Hi I've been using the package and I quite like it.

I'd be interested in contributing to the library by adding up type hints because it's always nice to have good more confidence in code correctness and more autocomplete for the users.

If that's something you think is a good idea, I'd try to work in small chunks. I think the best way to do would be to start with a first PR that sets up configure mypy and setup CI. The goal would be to get that in a working state with minimal changes.  Probably needs to fix a few types and maybe add typing to one file or two. Then I could incrementally add types and check more files in subsequent PRs.

### PR DESCRIPTION
**Pull request by enadeau**
This is the last step to close #373 !!!

## Description

Just adding the marking file to mark the package as PEP 561 compliant

## Type of change

Select the statement best describes this pull request.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] This is a documentation update
- [x] Other (please describe)

## Does your PR include tests

If you are fixing a bug or adding a feature, we appreciate (but do not require)
tests to support whatever fix of feature you're implementing.

- [ ] Yes
- [ ] No, i'd like some help with tests
- [x] This change doesn't require tests

## Did you include your contribution to the change log?

- [x] Yes, `changelog.md` is up-to-date.

### CODE REVIEW

**Comment by enadeau** [comment]
I'm really excited to get that done!

Once merge I'll need to check with test pypi to be sure the file is included correctly and everything works.

@lwasser  when you make the change to the src layout you'll have to be careful not break that. There's seems to be an additional config needed in with that layout https://setuptools.pypa.io/en/latest/userguide/datafiles.html#package-data

**Comment by lwasser** [comment]
> @lwasser when you make the change to the src layout you'll have to be careful not break that. There's seems to be an additional config needed in with that layout https://setuptools.pypa.io/en/latest/userguide/datafiles.html#package-data

yes!! lucky for us i'm actually working on a [python package guide](https://www.pyopensci.org/python-package-guide/) and have spent some time talking with PyPA folks about these tools and others. I setup the original setuptools / setuptools scm config in the fall when i was initially doing that research. so i do know how to make the changes! i just didn't want to make too many changes at once in the fall because it was a fairly big overhaul of all of the infrastructure for the package!

but i'll be sure to unpack the wheel and such before pushing here as a PR to ensure things install, unpack as they should. it's actually working well locally but i need to do a few more tests before opening a pr. 🎉  i'll have a closer look at this pr tomorrow and then we can merge it as well. yahoo!!!

**Comment by lwasser** [comment]
oh also -- we can actually test that the file lives in the wheel and sdist now. the wheel is just a zip file so you can just modify the extension and unzip it to see if the files are added correctly. i can also look tomorrow.but we don't need to wait for a push to test pypi to test that the typing file is being added to our package archives correctly.

**Review by lwasser — APPROVED** [review]
ok so this is what the unpacked wheel looks like - and the mypy file is there. i don't fully understand how that file works with mypy / what the benefits are to the user but do see the spec in the PEP. do you happen to know how the file behaves? it's empty but somehow it tells the user's gui to provide type hints?? 

Screen Shot 2023-08-29 at 2 34 37 PM

Other than that i can install from the wheel and import stravalib so all seems to be working. 
if you can help me understand what that file does i'd appreciate it! if not I can ask pypa folks!

**Comment by lwasser** [comment]
ok so i'll go ahead and merge this. i left a question for you in the recently-opened bot pr. but this PR is solid and we're just about (or ready??) for a 1.5 release with the python 3.8 drop i think???

**Comment by enadeau** [comment]
The file is mandatory to have type checker analyze our library when used as a third party. If we don't include it user will get this mypy warning when importing.
```
foo.py:1: error: Skipping analyzing "stravalib.client": module is installed, but missing library stubs or py.typed marker  [import]
```

You can read more about it https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-library-stubs-or-py-typed-marker

That being said I don't know more about the rationale behind this desingn

**Pull request merged**
