### PR TITLE
Fix: CI broken given new src layout

### LINKED ISSUE #438: BUG: Failed action - stravalib model check
https://github.com/stravalib/stravalib/actions/workflows/check-strava-api.yml

### Issue Description

This is related to several failing builds of the strava_model.py action. it can't seem to find the swagger.json file. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by lwasser**
closes #438 

## Description

I BROKE @jsamoocha ci build. 
## Type of change

Select the statement best describes this pull request.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] This is a documentation update
- [ ] Other (please describe)

## Does your PR include tests

If you are fixing a bug or adding a feature, we appreciate (but do not require)
tests to support whatever fix of feature you're implementing.

- [ ] Yes
- [ ] No, i'd like some help with tests
- [x] This change doesn't require tests (infrastructure fix)

## Did you include your contribution to the change log?

- [x] Yes, `changelog.md` is up-to-date.

y'all - this should fix the CI bug but let's see. it's referencing files that are now living in a src/ dir rather than a flat layout that we had before.

### CODE REVIEW

**Comment by lwasser** [comment]
I also just updated our pr template with a infrastructure option so we don't have to keep writing that option in.

**Comment by jsamoocha** [comment]
Great, that's fast and looks good. I tried testing it by running the workflow manually, but this branch must be in the stravalib repo itself for that to work. Let's merge and see if it works 🎲?

**Review by jsamoocha — APPROVED** [review]

**Comment by lwasser** [comment]
thanks! [it ran here (i just ran it)](https://github.com/lwasser/stravalib/actions/runs/6139018339/job/16656484806) and it's a 🟢 light! although didn't open a pr but i don't have the permissions for that setup in my fork! i'll merge now. this should fix things 🤞 . given the timing of when it broke i think it was my pr moving us to a src/ layout that broke things. but let's see.

**Comment by lwasser** [comment]
it seems to have[ run here too](https://github.com/stravalib/stravalib/actions/runs/6139039062)! ✨ BUT i guess it won't open a pr if there are no new changes?

**Pull request merged**
